seed: 1

num_cameras: 10
num_points: 200
average_track_length: 8
track_locality: 0.2

inner_optim:
  max_iters: 3
  step_size: 0.3
  backward_mode: full
  verbose: false
  track_err_history: true

outer_optim:
  lr: 0.1
  num_epochs: 20

hydra:
  run:
    dir: examples/outputs