seed: 1
solver_device: "cpu"

num_poses: 1024
dataset_size: 256 

inner_optim:
  optimizer_cls: GaussNewton
  solver: sparse
  max_iters: 10 
  step_size: 1
  verbose: true
  reg_w: 1e-3

hydra:
  run:
    dir: /private/home/taoshaf/Documents/theseus/examples/outputs/pose_graph_cube
  sweep:
    dir: /private/home/taoshaf/Documents/theseus/examples/outputs/pose_graph_cube/${now:%Y.%m.%d}/${now:%H.%M.%S}